# Configuration file for Mega-Linter
# See all available variables at https://megalinter.github.io/#configuration and in linters documentation

APPLY_FIXES: "all" # When true, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
FILTER_REGEX_EXCLUDE: (lib/example|\.github|\.vscode|pull_request_template|docs/javascripts)
DISABLE:
  - COPYPASTE
  - CSS
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
JAVASCRIPT_ES_FILE_NAME: "LINTER_DEFAULT"
FILEIO_REPORTER: true
PRINT_ALL_FILES: false
GITHUB_STATUS_REPORTER: false
PRE_COMMANDS:
  - continue_if_failed: false
    command: npm ci
    cwd: workspace