# Configuration file for Mega-Linter
# See all available variables at https://megalinter.io/#configuration and in linters documentation

APPLY_FIXES: "all" # When true, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
FILTER_REGEX_EXCLUDE: (lib/example|\.github|\.vscode|pull_request_template|docs/javascripts|package-lock\.json)
DISABLE:
  - COPYPASTE
  - CSS
JAVASCRIPT_DEFAULT_STYLE: prettier
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TYPESCRIPT_STANDARD
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_SEMGREP
  - SPELL_LYCHEE
FLAVOR_SUGGESTIONS: true
JAVASCRIPT_ES_FILE_NAME: "LINTER_DEFAULT"
GITHUB_STATUS_REPORTER: false
PRE_COMMANDS:
  - continue_if_failed: false
    command: npm ci
    cwd: workspace
