---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: 'Build & Deploy - Beta'
on:
  push:
    branches:
      - main
      - master

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

###############
# Set the Job #
###############
jobs:
  deploy:
    name: Deploy beta
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: beta
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: nvuillam
      - run: npm ci
      - run: BETAID=$(date '+%Y%m%d%H%M') && npm version prerelease --preid="beta$BETAID"
        shell: bash
      - run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
